name: Build & Publish AKSPAlinux ISO

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'pouya3767/AKSPAlinux'
    runs-on: ubuntu-latest # os 

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Start Arch Linux container
        run: |
          docker run -d --name archiso \
            --privileged \
            -v $PWD:/workspace \
            archlinux:latest tail -f /dev/null

      - name: Install archiso tools
        run: |
          docker exec archiso pacman -Sy --noconfirm
          docker exec archiso pacman -S --noconfirm \
            archiso git squashfs-tools xorriso grub

      - name: Build ISO
        run: |
          docker exec archiso bash -lc "
            cd /workspace &&
            mkdir -p out &&
            mkarchiso -v releng -o out
          " # making the iso

      - name: Copy ISO out of container
        run: |
          docker exec archiso bash -lc "cp /workspace/out/*.iso /workspace"
      - name: Stop container
        if: always()
        run: docker stop archiso

      - name: Clone ISO repository
        run: |
          git clone https://x-access-token:${{ secrets.ISO_PUSH_TOKEN }}@github.com/pouya3767/AKSPAISO.git iso-repo # cloning the AKSPAISO repo for pushing the result

      - name: Push ISO to AKSPAISO repo
        run: |
          ISO_FILE=$(ls out/*.iso | head -n 1)

          cp "$ISO_FILE" iso-repo/

          cd iso-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add *.iso
          git commit -m "New AKSPAlinux ISO build ($(date +'%Y-%m-%d'))" # making the commit
          git push # pushing the results

